version: "2.1"
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: root
    environment:
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
    volumes:
      - ~/.config:/config
      - ~/project:/home/coder/project
    ports:
      - 8080:8080
      - 8082:8082
    restart: unless-stopped